[project]
name = "perplex-term"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "langroid[chromadb]>=0.47.2",
    "numpy<2.0",
]
